TRAIN:
  train_data_dir: [
    '/data/guohang/dataset/TextZoom/train1',
    '/data/guohang/dataset/TextZoom/train2',
  ]
  featureSR_lr: 0.001
  Recognizer_lr: 0.00005
  batch_size: 64
  cuda: True
  width: 64
  height: 16
  epochs: 500
  ngpu: 1
  workers: 0
  resume: '/data/guohang/KD-STR/ckpt/ABINet-LTR.pth'
  ckpt_dir: './ckpt'
  voc_type: 'all'
  saveInterval: 200
  displayInterval: 50
  beta1: 0.5
  max_len: 25
  down_sample_scale: 2

  VAL:
    val_data_dir: [
      '/data/guohang/dataset/TextZoom/test/easy',
      '/data/guohang/dataset/TextZoom/test/medium',
      '/data/guohang/dataset/TextZoom/test/hard',
#        '/data/guohang/dataset/IC15',
#        '/data/guohang/dataset/IC13',
#        '/data/guohang/dataset/CUTE80',
#        '/data/guohang/dataset/SVTP',
#        '/data/guohang/dataset/SVT',
    ]
    valInterval: 400


ABINet:
  dataset_charset_path: './dataset/charset_36.txt'
  dataset_max_length: 25
  model_vision_attention_mode: 'nearest'
  full_ckpt: '/data/guohang/pretrained/ABINet-pretrained/train-abinet/best-train-abinet.pth'
  vision: {
    checkpoint: '/data/guohang/pretrained/ABINet-pretrained/pretrain-vision-model/best-pretrain-vision-model.pth',
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
    d_model: 512
  }
  language: {
    checkpoint: '/data/guohang/pretrained/ABINet-pretrained/pretrain-language-model/pretrain-language-model.pth',
    num_layers: 4,
    detach: True,
    use_self_attn: False
  }


MATRN:
  dataset_charset_path: './dataset/charset_36.txt'
  dataset_max_length: 25
  model_vision_attention_mode: 'nearest'
  full_ckpt: '/data/guohang/pretrained/ABINet-pretrained/best-train-matrn.pth'
  vision: {
    checkpoint: ,
    attention: 'position',
    backbone: 'transformer',
    backbone_ln: 3,
    d_model: 512
  }
  language: {
    checkpoint: ,
    num_layers: 4,
    detach: True,
    use_self_attn: False
  }



PARSeq:
  full_ckpt: '/data/guohang/pretrained/PARSeq.pth'
  img_size: [32,128]
  patch_size: [4,8]
  embed_dim: 384
  enc_depth: 12
  enc_num_heads: 6
  enc_mlp_ratio: 4

  self.max_label_length: 25
  self.decode_ar: True
  self.refine_iters: 1

  dec_num_heads: 12
  dec_mlp_ratio: 4
  dropout: 0.1
  dec_depth: 1
  perm_num: 6
  perm_mirrored: True
  max_label_length: 25


